# Generated by Django 4.2.10 on 2024-05-23 18:39

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("activName", models.TextField(max_length=100, verbose_name="Имя")),
                ("activDate", models.DateField(verbose_name="Дата")),
                (
                    "activLink",
                    models.TextField(blank=True, default="", verbose_name="Ссылка"),
                ),
                (
                    "activPlace",
                    models.IntegerField(blank=True, default=0, verbose_name="Место"),
                ),
                (
                    "activCertif",
                    models.FileField(
                        blank=True,
                        default="",
                        upload_to="media/user_cert",
                        verbose_name="Сертификат",
                    ),
                ),
                (
                    "activOther",
                    models.TextField(
                        blank=True, default="", verbose_name="Иное подтверждение"
                    ),
                ),
                (
                    "activAddit",
                    models.TextField(
                        blank=True,
                        default="",
                        verbose_name="Допоплнительная информация",
                    ),
                ),
            ],
        ),
    ]
