# Generated by Django 4.2.13 on 2024-05-23 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='activAddit',
            field=models.TextField(blank=True, default='', verbose_name='Допоплнительная информация'),
        ),
        migrations.AlterField(
            model_name='report',
            name='activCertif',
            field=models.FileField(blank=True, default='', upload_to='media/user_cert', verbose_name='Сертификат'),
        ),
        migrations.AlterField(
            model_name='report',
            name='activLink',
            field=models.TextField(blank=True, default='', verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='report',
            name='activOther',
            field=models.TextField(blank=True, default='', verbose_name='Иное подтверждение'),
        ),
        migrations.AlterField(
            model_name='report',
            name='activPlace',
            field=models.IntegerField(blank=True, default='', verbose_name='Место'),
        ),
    ]
