# Generated by Django 4.2.13 on 2024-05-23 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_alter_report_activaddit_alter_report_activcertif_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='activDate',
            field=models.DateField(verbose_name='Дата'),
        ),
    ]
