# Generated by Django 4.2.13 on 2024-05-23 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_alter_report_activdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='activPlace',
            field=models.IntegerField(blank=True, default=0, verbose_name='Место'),
        ),
    ]
